import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from 'typeorm';

/**
 * AdminCorrectionLedger
 *
 * Append-only audit ledger for all admin-initiated balance / fee corrections.
 * Rows are NEVER updated or deleted — only inserted.  This guarantees a
 * tamper-evident history that finance teams can reconcile against the
 * live transaction table at any time.
 *
 * Finance-safety guarantees enforced in AdminLedgerService:
 *  - No update / delete methods are exposed.
 *  - Reconciliation helpers return running totals grouped by targetId so
 *    discrepancies surface immediately.
 */
export enum CorrectionType {
  BALANCE_CREDIT = 'BALANCE_CREDIT',
  BALANCE_DEBIT = 'BALANCE_DEBIT',
  FEE_WAIVER = 'FEE_WAIVER',
  FEE_ADJUSTMENT = 'FEE_ADJUSTMENT',
  INTEREST_CORRECTION = 'INTEREST_CORRECTION',
  OTHER = 'OTHER',
}

@Entity('admin_correction_ledger')
@Index('idx_acl_target_id', ['targetId'])
@Index('idx_acl_admin_id', ['adminId'])
@Index('idx_acl_request_id', ['requestId'])
@Index('idx_acl_workflow_id', ['workflowId'])
@Index('idx_acl_created_at', ['createdAt'])
export class AdminCorrectionLedger {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * The entity being corrected (e.g. transaction id, subscription id, user id).
   * Deliberately a plain string so it can reference different resource types.
   */
  @Column({ type: 'varchar', length: 255 })
  targetId: string;

  /**
   * Human-readable resource type (e.g. 'transaction', 'subscription', 'fee').
   */
  @Column({ type: 'varchar', length: 64 })
  targetType: string;

  /** UUID of the admin who created this correction. */
  @Column({ type: 'uuid' })
  adminId: string;

  /** Machine-readable correction category. */
  @Column({ type: 'enum', enum: CorrectionType })
  correctionType: CorrectionType;

  /**
   * Signed correction amount (positive = credit, negative = debit).
   * Stored as text to preserve arbitrary-precision Stellar amounts.
   */
  @Column({ type: 'varchar', length: 64 })
  delta: string;

  /** Value of the field BEFORE this correction was applied. */
  @Column({ type: 'text', nullable: true })
  previousValue: string | null;

  /** Value of the field AFTER this correction was applied. */
  @Column({ type: 'text', nullable: true })
  newValue: string | null;

  /**
   * Free-text justification.  Mandatory on write — the service layer enforces
   * this via class-validator on the DTO.
   */
  @Column({ type: 'text' })
  reason: string;

  /**
   * Correlation / idempotency key from the HTTP request (X-Request-Id header
   * or generated by the caller).  Used to detect double-submissions.
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  requestId: string | null;

  /**
   * Optional external workflow / ticket identifier (e.g. a support-ticket id,
   * Jira key, or internal approval-workflow id).
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  workflowId: string | null;

  /** Arbitrary JSON blob for additional context (e.g. before/after snapshots). */
  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, unknown> | null;

  /**
   * Immutable creation timestamp.  Never populated via @UpdateDateColumn so
   * the row remains read-only after insert.
   */
  @CreateDateColumn()
  createdAt: Date;
}
